### ISSUE TITLE
Parent category not assigned when mapped slug field uses PascalCase

### ISSUE THREAD

**Issue by zackspear** [craftcms/feed-me#1173]
### Description

I have a JSON feed that I use to import categories and sub-categories. My issue lies with parent categories not correctly being assigned on sub-categories when the source JSON uses PascalCase for the category slug.

Feed map settings
![Screen Shot 2022-08-05 at 14 14 16](https://user-images.githubusercontent.com/2531682/183200278-d26d91ce-aab0-41f3-93cf-61dcb5ee531f.png)

PascalCase.json
```json
[
  {
    "Cat": "MediaApp",
    "Des": "Media Applications"
  },
  {
    "Cat": "MediaApp-Books",
    "Des": "Books",
    "parentCat": "MediaApp"
  },
  {
    "Cat": "MediaApp-Music",
    "Des": "Music",
    "parentCat": "MediaApp"
  },
  {
    "Cat": "MediaApp-Photos",
    "Des": "Photos",
    "parentCat": "MediaApp"
  },
  {
    "Cat": "MediaApp-Video",
    "Des": "Video",
    "parentCat": "MediaApp"
  },
  {
    "Cat": "MediaApp-Other",
    "Des": "Other",
    "parentCat": "MediaApp"
  }
]
```

In the feed settings I have the `Cat` field assigned to the `slug` of the category. When the feed runs the PascalCase `Cat` field is converted to `kebab-case` - so `MediaApp` turns into `media-app` and `MediaApp-Books` becomes `media-app-books`.

The issue lies in the sub-category creation/update as `media-app` is not assigned as the parent category of `media-app-books`.

I was able to figure this out after tinkering with the JSON file and changing PascalCase to kebab-case. And when I tested kebab-case the feed import ran just fine and correctly assigned parent categories.

So perhaps the issue lies in the conversion of the provided string to kebab-case.

### Additional info
 
- PHP version 7.4.30
- Linux 5.4.0-1078-aws
- MySQL 5.5.5
- GD 7.4.30
- Craft Pro 3.7.45.1

**Comment by i-just** [comment]
Hi, thanks for getting in touch. There are 3 options to achieve what you’re after:

1. normalise slug values in your json so that they are kebab-case
2. add a custom field to your category group to hold the exact value specified in `Cat` and match elements based on that field and not the slug
3. use [`allowUppercaseInSlug`](https://craftcms.com/docs/3.x/config/config-settings.html#allowuppercaseinslug) and [`slugWordSeparator`](https://craftcms.com/docs/3.x/config/config-settings.html#slugwordseparator) general config settings to adjust how the slugs should look across your website. If you set `allowUppercaseInSlug` to `true` and `slugWordSeparator` to `''`, it will be possible to use Pascal Case slugs.

I hope this helps you. 
I’m going to close this issue now, but if you have any further problems, please feel free to reply.
