### ISSUE TITLE
Migration failure updating to 4.5.4

### ISSUE THREAD

**Issue by pixelmachine** [craftcms/feed-me#1222]
### Description

```
applying m201106_202042_singleton_feeds

> add column singleton boolean NOT NULL DEFAULT FALSE AFTER `sortOrder` to table {{%feedme_feeds}} ...Exception: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'singleton'

The SQL being executed was: ALTER TABLE `craft_feedme_feeds` ADD `singleton` tinyint(1) NOT NULL DEFAULT FALSE AFTER `sortOrder` (/Users/sitename/craft3/vendor/yiisoft/yii2/db/Schema.php:676)
```
Related to #1096 ?

### Steps to reproduce

1. Run update to update Feed Me from 4.5.3 to 4.5.4 among others
2. Migration fails, roll back to previous

### Additional info

- Craft version: 3.7.61 
- PHP version: 8.1.1
- Database driver & version: mysql 5.7.34

**Comment by angrybrad** [comment]
That error indicates the column already exists, which means the migration must have run before. Usually, that happens when an update is attempted and failed (for whatever reason), and the database wasn’t restored from a pre-update attempt database backup before the next update was tried.

Guessing that’s what happened here as well.
