### ISSUE TITLE
Element type not found

### ISSUE THREAD

**Issue by MarcelWeidum** [craftcms/feed-me#500]
### Description
After updating to 3.1.16 I can't find the element type 'Product' or 'Variant'. By existing feeds with that type I get this error: 'Element group not found by Element type craft\commerce\elements\Product'.

### Steps to reproduce

1. Install update (3.1.12 to 3.1.16)

### Additional info

- Plugin version: 3.1.16
- Craft version: 3.1.19

**Comment by ul8** [comment]
Same issue here. Previously created feeds using `Category` or `User` element type no longer work with messages "craft\elements\Category"  "Element group not found".

I just ran composer update and am updated to Craft 3.1.21 and Feedme 3.1.16. 

Previously installed versions (Feedme 3.1.15 and Craft 3.1.18) had the same issue.

**Comment by ul8** [comment]
PS: the last good version of the plugin is 3.1.13

**Comment by engram-design** [comment]
This might be related to the editions change. Previously, you would've had Feed Me Pro and Feed Me plugins installed in order to import other elements. When updating to the latest versions, Feed Me will switch to the Lite version, which will disable functionality and throw errors as per the above.

Can you confirm if you've followed the steps here - https://github.com/verbb/feed-me#editions - and you're on a trial or full version of the Pro edition?

**Comment by ul8** [comment]
@engram-design Thanks, that was it! Must say though it's odd to make a breaking change like this in a patch release.

**Comment by brandonkelly** [comment]
This should no longer be an issue since there's [just one edition now](https://craftcms.com/blog/feed-me).
