### ISSUE TITLE
Possibility to map a feed in a config file (not through admin)

### ISSUE THREAD

**Issue by stigzelm** [craftcms/feed-me#668]
### Description
It would be really useful if you could override a feeds mapping through a config.php file. The same way we are overriding siteUrl in the general.php file.

**Comment by KONEY** [comment]
We have the same need because our feed are pretty big and take quite sometime to process. So to change a simple field mapping it takes some twenty minutes.

Alternatively some documentation on how settings are saved would be helpful, at this point reading the content of feedme_feeds table, fieldMapping is quite confusing.
