### ISSUE TITLE
Let an asset be imported from an ID that Craft export provides

### ISSUE THREAD

**Issue by texasbaptists** [craftcms/feed-me#767]
I need to migrate entries from an old section to a new one. When entries with an asset field (in my case a featured image) are exported from Craft, the JSON data gives an asset ID. It would be super helpful if I could import this JSON into the new section and the asset field be populated with the assets that are already in the system by ID. 

Here's an example of how an asset field shows up when exporting craft entries:

```
        "featuredImage": [
            "168975"
        ],
```

**Comment by cole007** [comment]
100% could do with this feature

**Comment by johnj24** [comment]
I could use this feature as well. Element Exporter and Feed Me do not feel 100% compatible otherwise. I posed this question in April 2020 and did get one response recently if it helps anyone: https://craftcms.stackexchange.com/questions/35215/importing-assets-with-feed-me-using-element-exporter-data
